name: Common Workflow

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
        description: "Node.js 버전"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: TypeScript type check
        run: yarn tsc --noEmit
        continue-on-error: true

      - name: Run linting
        run: yarn lint
        continue-on-error: true

      - name: Run tests
        run: yarn test

      - name: Build project
        run: yarn build
