name: PR Test and Validation # Runs when a PR is created or updated

on:
  pull_request:
    types: [opened, synchronize, reopened] # Trigger on PR open, update, or reopen
    branches: [main] # Only for PRs targeting the main branch

jobs:
  validate:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner
    strategy:
      matrix:
        node-version: [18.x, 20.x] # Test across multiple Node.js versions supported in package.json

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn" # Cache Yarn dependencies

      # Install dependencies
      - name: Install dependencies
        run: yarn install

      # TypeScript type checking
      - name: TypeScript type check
        run: yarn tsc --noEmit

      # Run linter
      - name: Run linter
        run: yarn lint

      # Run tests
      - name: Run tests
        run: yarn test
